DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    IND         INTEGER PRIMARY KEY     NOT NULL,
    USERNAME    VARCHAR(32)             NOT NULL UNIQUE,
    PASSWORD    VARCHAR(32)             NOT NULL
);

DROP TABLE IF EXISTS ONLINEMUSICS;
CREATE TABLE ONLINEMUSICS
(
    IND         INTEGER PRIMARY KEY     NOT NULL,
    NAME        VARCHAR(128)            NOT NULL UNIQUE,
    AUTHOR      VARCHAR(32)             NOT NULL,
    CREATETIME  DATETIME                NOT NULL,
    MUSICLINK   VARCHAR(128)            NOT NULL
);